### ISSUE TITLE
Add project description

### ISSUE THREAD

**Issue by tukkek** [diddlesnaps/starruler2#1]
Hi Daniel and thanks for this Snap - which I've found from your PSA on the original repository!

This is a very minor request but could you add a description to the project itself, so I and others can know what it is about when browsing their stars, instead of having to open the project and see the README?

I think this would be perfect:

> This is the snap for Star Ruler 2, "A massive scale 4X/RTS set in space".

You may also want to add a website URL linking to the official SR2 website, to promote further sales.

**Comment by lucyllewy** [comment]
aha. Thanks for the reminder :-) I've added the description so you should be good now.. :+1:

**Comment by tukkek** [comment]
You really should add something about Snap to the description since this is the whole point of your fork!
