### ISSUE TITLE
building with or without harfbuzz

### ISSUE THREAD

**Issue by goulart81** [diddlesnaps/starruler2#4]
https://github.com/diddlesnaps/starruler2/blob/e32b6332823b9dd5a0093fac45ad9184a7ce363b/snap/snapcraft.yaml#L148

Building harfbuzz as a separate lib and at the same time building freetype without harfbuzz (--without-harfbuzz).  Is this correct ? Is harfbuzz being used ?

**Comment by lucyllewy** [comment]
That is correct. There are two freetype parts: `freetype-prebuild` and `freetype`. The first builds a minimal freetype to satisfy the harfbuzz+freetype circular dependency and then the second builds freetype with the harfbuzz that has broken out of the circle.
